In [1]:
import numpy as np

In [11]:
# An array that has 1-D arrays as its elements is called a 2-D array
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
# These are the most common and basic arrays.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d)
print(type(a))
# To find out how many dimensions your numpy array is having
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
0
1
2
3


In [20]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

arr1=np.array([1,2,3])
for i in arr1:
    print(i)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
1
2
3


In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [18]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

for i in arr:
    for j in i:
       print(j)

Last element from 2nd dim:  10
1
2
3
4
5
6
7
8
9
10


In [21]:
# Access the third element of 2nd row of 1st array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

# Iterating means going through elements one by one 
for i in arr:
    for j in i:
        for k in j:
            print(k)

6
1
2
3
4
5
6
7
8
9
10
11
12


In [23]:
# Iterate over ndarray using nditer() method
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [25]:
#Sorting means putting elements in an ordered sequence.
#Ordered sequence is any sequence that has an order corresponding to elements,
# like numeric or alphabetical, ascending or descending.

arr = np.array([[[3, 2],[4,1]],[[1,2],[3,0]]])

print(np.sort(arr))


[[[2 3]
  [1 4]]

 [[1 2]
  [0 3]]]


In [28]:
#You can search an array for a certain value, and return the indexes that get a match.
#To search an array, use the where() method.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

arr1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
x = np.where(arr1 == 5)

print(x)

(array([1, 3, 5, 7], dtype=int64),)
(array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64))
